spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: default
    url: jdbc:mysql://127.0.0.1:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  ## Freemarker 配置
  freemarker:
    template-loader-path: classpath:/templates
    cache: true
    charset: utf-8
    content-type: text/html
    suffix: .ftl
    expose-spring-macro-helpers: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    check-template-location: true
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##########
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:s
      classic_compatible: true
      template_exception_handler: ignore

mybatis:
  basepackage: com.xxl.job.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"
quartz:
  configLocation: quartz.properties

#xxl-job配置
xxl:
  job:
    ### xxl-job email
    mail:
      host: smtp.163.com
      port: 25
      ssl: false
      username: xx@xx
      password: 123456
      sendNick: '《任务调度平台XXL-JOB》'
    ### xxl-job login
    login:
      username: admin
      password: 123456
    ### xxl-job, access token
    accessToken: 'token'
    ### xxl-job, i18n (default empty as chinese, "en" as english)
    i18n: ''
  #执行器基础定义
  jobInfo:
    jobGroup: 2  #执行器主键ID	XXL_JOB_QRTZ_TRIGGER_GROUP.id
    jobCronEveryDay: '0 0 2 * * ?' #每天凌晨2点执行
    jobCronManual: '0 0 2 * * ? 2099' #手动执行
    executorFailStrategy: FAIL_ALARM # 失败处理策略(FAIL_ALARM(失败警告)/FAIL_RETRY(失败重试))
    author: 'system' # 责任人
    alarmEmail: '' # 报警邮件 多个邮箱,分割
    executorRouteStrategy: ROUND  #路由策略
    glueType: BEAN  #运行模式 Bean模式
    executorHandler: sparkJobHandler #执行JobHandler方法
    executorBlockStrategy: SERIAL_EXECUTION #阻塞处理策略 单机串行

###################################
# 日志配置
###################################
logging:
  level:
    root: info
    xxl.job.admin: debug
#    path: /Users/wfeng/efuture/workspaces/ews-all/engine-spark/logs

##Druid config
druid:
  username: future
  password: future123